catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
overrides:
  "@vercel/nft": ^0.27.4

catalogs:
  default:
    "@ai-sdk/openai": ^2.0.88
    "@aws-sdk/client-s3": ^3.954.0
    "@iconify-json/carbon": ^1.2.15
    "@iconify-json/lucide": ^1.2.81
    "@iconify-json/mdi": ^1.2.3
    "@iconify-json/simple-icons": ^1.2.63
    "@jannchie/eslint-config": ^3.7.5
    "@libsql/client": ^0.15.15
    "@nuxt/eslint": 1.12.1
    "@nuxt/hints": 1.0.0-alpha.4
    "@nuxt/icon": ^2.1.1
    "@nuxt/image": 2.0.0
    "@nuxt/test-utils": 3.21.0
    "@nuxt/ui": 4.3.0
    "@nuxtjs/i18n": ^10.2.1
    "@nuxtjs/seo": ^3.3.0
    "@sentry/nuxt": ^10.32.0
    "@types/node": ^25.0.3
    "@vite-pwa/nuxt": ^1.1.0
    "@vueuse/core": ^14.1.0
    ai: ^5.0.115
    chart.js: ^4.5.1
    dotenv: ^17.2.3
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    eslint: ^9.39.2
    exifr: ^7.1.3
    import-in-the-middle: ^2.0.0
    nuxt: ^4.2.2
    png-to-ico: ^3.0.1
    sharp: ^0.34.5
    tailwindcss: ^4.1.18
    tailwindcss-safe-area: 1.2.0
    thumbhash: ^0.1.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    vue: ^3.5.26
    vue-router: ^4.6.4
    vue-wf: ^0.7.0
onlyBuiltDependencies:
  - "@sentry/cli"
  - vue-demi
