catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
overrides:
  "@vercel/nft": ^0.27.4
catalogs:
  default:
    "@ai-sdk/openai": ^2.0.77
    "@aws-sdk/client-s3": ^3.946.0
    "@iconify-json/carbon": ^1.2.15
    "@iconify-json/mdi": ^1.2.3
    "@iconify-json/simple-icons": ^1.2.61
    "@jannchie/eslint-config": ^3.7.4
    "@libsql/client": ^0.15.15
    "@nuxt/eslint": 1.11.0
    "@nuxt/hints": 1.0.0-alpha.3
    "@nuxt/icon": ^2.1.0
    "@nuxt/image": 2.0.0
    "@nuxt/test-utils": 3.21.0
    "@nuxt/ui": 4.2.1
    "@nuxtjs/i18n": ^10.2.1
    "@nuxtjs/seo": ^3.2.2
    "@prisma/adapter-libsql": ^7.1.0
    "@prisma/client": ^7.1.0
    "@sentry/nuxt": ^10.29.0
    "@vite-pwa/nuxt": ^1.1.0
    "@vueuse/core": ^14.1.0
    ai: ^5.0.107
    chart.js: ^4.5.1
    dotenv: ^17.2.3
    eslint: ^9.39.1
    exifr: ^7.1.3
    import-in-the-middle: ^2.0.0
    nuxt: ^4.2.1
    png-to-ico: ^3.0.1
    prisma: ^7.1.0
    sharp: ^0.34.5
    tailwindcss: ^4.1.17
    tailwindcss-safe-area: 1.2.0
    thumbhash: ^0.1.1
    tsx: ^4.21.0
    typescript: ^5.9.3
    vue: ^3.5.25
    vue-router: ^4.6.3
    vue-wf: ^0.7.0
onlyBuiltDependencies:
  - "@sentry/cli"
  - vue-demi
