#!/usr/bin/env sh
set -e

# Map unprefixed admin vars to the prefixes Nitro/NUXT reads.
ADMIN_USERNAME_RESOLVED="${NITRO_ADMIN_USERNAME:-${NUXT_ADMIN_USERNAME:-$ADMIN_USERNAME}}"
ADMIN_PASSWORD_RESOLVED="${NITRO_ADMIN_PASSWORD:-${NUXT_ADMIN_PASSWORD:-$ADMIN_PASSWORD}}"
ADMIN_SESSION_SECRET_RESOLVED="${NITRO_ADMIN_SESSION_SECRET:-${NUXT_ADMIN_SESSION_SECRET:-$ADMIN_SESSION_SECRET}}"
[ -n "$ADMIN_USERNAME_RESOLVED" ] && export NITRO_ADMIN_USERNAME="$ADMIN_USERNAME_RESOLVED" && [ -z "$NUXT_ADMIN_USERNAME" ] && export NUXT_ADMIN_USERNAME="$ADMIN_USERNAME_RESOLVED"
[ -n "$ADMIN_PASSWORD_RESOLVED" ] && export NITRO_ADMIN_PASSWORD="$ADMIN_PASSWORD_RESOLVED" && [ -z "$NUXT_ADMIN_PASSWORD" ] && export NUXT_ADMIN_PASSWORD="$ADMIN_PASSWORD_RESOLVED"
[ -n "$ADMIN_SESSION_SECRET_RESOLVED" ] && export NITRO_ADMIN_SESSION_SECRET="$ADMIN_SESSION_SECRET_RESOLVED" && [ -z "$NUXT_ADMIN_SESSION_SECRET" ] && export NUXT_ADMIN_SESSION_SECRET="$ADMIN_SESSION_SECRET_RESOLVED"

# Map unprefixed S3 vars to storage runtime config.
STORAGE_ENDPOINT_RESOLVED="${NITRO_STORAGE_ENDPOINT:-${NUXT_STORAGE_ENDPOINT:-$S3_ENDPOINT}}"
STORAGE_BUCKET_RESOLVED="${NITRO_STORAGE_BUCKET:-${NUXT_STORAGE_BUCKET:-$S3_BUCKET}}"
STORAGE_ACCESS_KEY_ID_RESOLVED="${NITRO_STORAGE_ACCESS_KEY_ID:-${NUXT_STORAGE_ACCESS_KEY_ID:-$S3_ACCESS_KEY_ID}}"
STORAGE_SECRET_ACCESS_KEY_RESOLVED="${NITRO_STORAGE_SECRET_ACCESS_KEY:-${NUXT_STORAGE_SECRET_ACCESS_KEY:-$S3_SECRET_ACCESS_KEY}}"
STORAGE_PUBLIC_BASE_URL_RESOLVED="${NITRO_STORAGE_PUBLIC_BASE_URL:-${NUXT_STORAGE_PUBLIC_BASE_URL:-$S3_PUBLIC_BASE_URL}}"
[ -n "$STORAGE_ENDPOINT_RESOLVED" ] && export NITRO_STORAGE_ENDPOINT="$STORAGE_ENDPOINT_RESOLVED" && [ -z "$NUXT_STORAGE_ENDPOINT" ] && export NUXT_STORAGE_ENDPOINT="$STORAGE_ENDPOINT_RESOLVED"
[ -n "$STORAGE_BUCKET_RESOLVED" ] && export NITRO_STORAGE_BUCKET="$STORAGE_BUCKET_RESOLVED" && [ -z "$NUXT_STORAGE_BUCKET" ] && export NUXT_STORAGE_BUCKET="$STORAGE_BUCKET_RESOLVED"
[ -n "$STORAGE_ACCESS_KEY_ID_RESOLVED" ] && export NITRO_STORAGE_ACCESS_KEY_ID="$STORAGE_ACCESS_KEY_ID_RESOLVED" && [ -z "$NUXT_STORAGE_ACCESS_KEY_ID" ] && export NUXT_STORAGE_ACCESS_KEY_ID="$STORAGE_ACCESS_KEY_ID_RESOLVED"
[ -n "$STORAGE_SECRET_ACCESS_KEY_RESOLVED" ] && export NITRO_STORAGE_SECRET_ACCESS_KEY="$STORAGE_SECRET_ACCESS_KEY_RESOLVED" && [ -z "$NUXT_STORAGE_SECRET_ACCESS_KEY" ] && export NUXT_STORAGE_SECRET_ACCESS_KEY="$STORAGE_SECRET_ACCESS_KEY_RESOLVED"
[ -n "$STORAGE_PUBLIC_BASE_URL_RESOLVED" ] && export NITRO_STORAGE_PUBLIC_BASE_URL="$STORAGE_PUBLIC_BASE_URL_RESOLVED" && [ -z "$NUXT_STORAGE_PUBLIC_BASE_URL" ] && export NUXT_STORAGE_PUBLIC_BASE_URL="$STORAGE_PUBLIC_BASE_URL_RESOLVED"

# Derive image proxy domains from the public URL when users do not set them.
extract_host() {
  value="$1"
  [ -z "$value" ] && return 0
  stripped="${value#*://}"
  host_port="${stripped%%/*}"
  host="${host_port%%:*}"
  [ -n "$host" ] && printf '%s' "$host"
}

IMAGE_DOMAIN_DEFAULT="$(extract_host "$STORAGE_PUBLIC_BASE_URL_RESOLVED")"
[ -n "$IMAGE_DOMAIN_DEFAULT" ] && [ -z "$NUXT_IMAGE_DOMAINS" ] && export NUXT_IMAGE_DOMAINS="$IMAGE_DOMAIN_DEFAULT"
[ -n "$IMAGE_DOMAIN_DEFAULT" ] && [ -z "$NUXT_IPX_HTTP_DOMAINS" ] && export NUXT_IPX_HTTP_DOMAINS="$IMAGE_DOMAIN_DEFAULT"
[ -n "$IMAGE_DOMAIN_DEFAULT" ] && [ -z "$NUXT_PUBLIC_IMAGE_DOMAINS" ] && export NUXT_PUBLIC_IMAGE_DOMAINS="$IMAGE_DOMAIN_DEFAULT"

exec "$@"
