/**
 * Regenerates `app/constants/brand-logo-paths.ts` from @iconify-json/simple-icons.
 * Run `pnpm logos:generate` after editing `brandIconKeys`, or after a
 * @iconify-json/simple-icons bump reshapes a logo.
 */
import { Buffer } from 'node:buffer'
import { writeFileSync } from 'node:fs'
import process from 'node:process'
import iconSet from '@iconify-json/simple-icons/icons.json' with { type: 'json' }
import sharp from 'sharp'
import { brandIconKeys } from '../app/constants/brand-icons'

const icons = (iconSet as { icons: Record<string, { body: string } | undefined> }).icons
const RASTER = 240

/**
 * Half of these logos are wordmarks that occupy a thin band of the 24x24
 * viewBox, so rendering them all in that box makes them illegibly small next
 * to text. Rasterizing once here gives the true ink bounds, which become a
 * tight viewBox the card can size by cap height instead.
 */
async function inkBounds(svg: string): Promise<[number, number, number, number]> {
  const { data, info } = await sharp(Buffer.from(svg))
    .resize(RASTER, RASTER)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })

  let minX = info.width
  let minY = info.height
  let maxX = -1
  let maxY = -1
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      if (data[(y * info.width + x) * info.channels + 3]! > 8) {
        minX = Math.min(minX, x)
        minY = Math.min(minY, y)
        maxX = Math.max(maxX, x)
        maxY = Math.max(maxY, y)
      }
    }
  }
  if (maxX < 0) {
    throw new Error('rasterized logo is empty')
  }
  const scale = 24 / RASTER
  const round = (value: number): number => Math.round(value * scale * 100) / 100
  return [round(minX), round(minY), round(maxX - minX + 1), round(maxY - minY + 1)]
}

const entries: string[] = []
for (const key of brandIconKeys) {
  const icon = icons[key]
  if (!icon) {
    throw new Error(`simple-icons has no icon named "${key}"`)
  }
  // Every simple-icon is a plain path set on a 24x24 viewBox; joining the `d`
  // attributes keeps one path element per logo.
  const d = [...icon.body.matchAll(/d="([^"]+)"/g)].map(match => match[1]).join(' ')
  if (d.length === 0) {
    throw new Error(`icon "${key}" has no path data`)
  }
  const box = await inkBounds(
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="${d}"/></svg>`,
  )
  entries.push(`  ${key}: { box: ${JSON.stringify(box)}, d: ${JSON.stringify(d)} },`)
}

const header = `/**
 * Brand logos for \`brandIconKeys\` as raw path data, plus each logo's ink
 * bounds within the 24x24 viewBox. Satori renders vnodes rather than markup,
 * so the OG card has to emit a literal <path d="...">, and the tight box lets
 * it size wordmarks and square marks to the same cap height.
 *
 * Generated by \`pnpm logos:generate\` — do not edit by hand.
 */
import type { BrandIconKey } from '~/constants/brand-icons'

/** \`box\` is [minX, minY, width, height] of the drawn ink. */
export interface BrandLogo {
  box: [number, number, number, number]
  d: string
}

`
writeFileSync(
  'app/constants/brand-logo-paths.ts',
  `${header}export const brandLogoPaths: Record<BrandIconKey, BrandLogo> = {\n${entries.join('\n')}\n}\n`,
)
process.stdout.write(`wrote ${entries.length} brand logo paths\n`)
